---
- name: master setup
  hosts: master

  tasks:
    - include_role:
        name: init
    
    - include_role:
        name: docker

    - name: kubeadm init
      become: yes
      shell: kubeadm init --kubernetes-version=
